import { useState } from "react";
import { Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import { ScreenContainer } from "@/components/screen-container";
import { IconSymbol } from "@/components/ui/icon-symbol";

const colors = { bg: "#07111F", surface: "#0D1B2A", border: "#1E3A56", text: "#E6F4FE", muted: "#8BA4B8", cyan: "#67E8F9" };

export default function ChatScreen() {
  const [prompt, setPrompt] = useState("");
  const [notice, setNotice] = useState("");
  function trySend() { setNotice("Nenhum modelo local está carregado. A mensagem não foi enviada e nenhuma resposta foi inventada."); }
  return <ScreenContainer className="px-5" containerClassName="bg-background"><View style={styles.content}><Text style={styles.eyebrow}>CLUSTERAI / CHAT</Text><Text style={styles.title}>Conversa local</Text><View style={styles.status}><IconSymbol name="memory" size={21} color={colors.cyan} /><View style={{ flex: 1 }}><Text style={styles.statusTitle}>Modelo não disponível</Text><Text style={styles.statusBody}>Carregue um arquivo compatível para ativar a geração.</Text></View></View><View style={styles.empty}><View style={styles.emptyIcon}><IconSymbol name="paperplane.fill" size={22} color={colors.cyan} /></View><Text style={styles.emptyTitle}>Sem mensagens ainda</Text><Text style={styles.emptyBody}>Este chat usará somente o modelo local selecionado. Quando a inferência distribuída estiver pronta, o status de cada nó aparecerá aqui.</Text></View><View style={styles.composer}><TextInput value={prompt} onChangeText={setPrompt} editable={false} placeholder="Escreva uma mensagem…" placeholderTextColor={colors.muted} style={styles.input} /><Pressable onPress={trySend} style={({ pressed }) => [styles.send, pressed && { opacity: .7 }]}><IconSymbol name="paperplane.fill" size={18} color={colors.bg} /></Pressable></View>{notice ? <Text style={styles.notice}>{notice}</Text> : null}</View></ScreenContainer>;
}
const styles = StyleSheet.create({ content: { paddingTop: 18 }, eyebrow: { color: colors.cyan, fontSize: 11, fontWeight: "800", letterSpacing: 1.5 }, title: { color: colors.text, fontSize: 30, fontWeight: "800", marginTop: 4 }, status: { flexDirection: "row", alignItems: "center", gap: 12, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border, borderRadius: 16, padding: 14, marginTop: 24 }, statusTitle: { color: colors.text, fontSize: 13, fontWeight: "800" }, statusBody: { color: colors.muted, fontSize: 11, marginTop: 4 }, empty: { alignItems: "center", borderWidth: 1, borderColor: colors.border, borderStyle: "dashed", borderRadius: 18, padding: 24, marginTop: 18 }, emptyIcon: { width: 46, height: 46, borderRadius: 15, backgroundColor: "#14324B", alignItems: "center", justifyContent: "center", marginBottom: 11 }, emptyTitle: { color: colors.text, fontSize: 15, fontWeight: "800" }, emptyBody: { color: colors.muted, fontSize: 11, lineHeight: 17, textAlign: "center", marginTop: 8 }, composer: { flexDirection: "row", alignItems: "center", gap: 8, marginTop: 22 }, input: { flex: 1, borderWidth: 1, borderColor: colors.border, borderRadius: 14, paddingHorizontal: 14, paddingVertical: 13, color: colors.muted, backgroundColor: colors.surface }, send: { width: 46, height: 46, borderRadius: 14, backgroundColor: colors.cyan, alignItems: "center", justifyContent: "center" }, notice: { color: colors.cyan, fontSize: 11, lineHeight: 16, marginTop: 16, backgroundColor: "#12283A", borderRadius: 12, padding: 12 } });
