import { StyleSheet, Text, View } from "react-native";
import { ScreenContainer } from "@/components/screen-container";
import { IconSymbol } from "@/components/ui/icon-symbol";

const colors = { surface: "#0D1B2A", border: "#1E3A56", text: "#E6F4FE", muted: "#8BA4B8", cyan: "#67E8F9", amber: "#FBBF24" };

export default function ModelScreen() {
  return <ScreenContainer className="px-5" containerClassName="bg-background"><View style={styles.content}><Text style={styles.eyebrow}>CLUSTERAI / MODELO</Text><Text style={styles.title}>Modelos locais</Text><View style={styles.empty}><View style={styles.icon}><IconSymbol name="memory" size={23} color={colors.amber} /></View><Text style={styles.heading}>Nenhum modelo encontrado</Text><Text style={styles.body}>Esta tela só exibirá modelos que existam no armazenamento do aparelho e passem pela validação do runtime. O aplicativo não assume tamanho, quantização ou nome de modelo.</Text></View><View style={styles.info}><Text style={styles.label}>PRÓXIMA INTEGRAÇÃO</Text><Text style={styles.infoTitle}>Runtime Android</Text><Text style={styles.body}>A integração deverá carregar GGUF via llama.cpp ou um módulo ExecuTorch/PTE. Depois disso, memória exigida, contexto e compatibilidade serão lidos dos metadados reais.</Text></View></View></ScreenContainer>;
}
const styles = StyleSheet.create({ content: { paddingTop: 18 }, eyebrow: { color: colors.cyan, fontSize: 11, fontWeight: "800", letterSpacing: 1.5 }, title: { color: colors.text, fontSize: 30, fontWeight: "800", marginTop: 4 }, empty: { alignItems: "center", borderWidth: 1, borderColor: colors.border, borderStyle: "dashed", borderRadius: 18, padding: 24, marginTop: 24 }, icon: { width: 48, height: 48, borderRadius: 15, backgroundColor: "#3A2C14", alignItems: "center", justifyContent: "center", marginBottom: 12 }, heading: { color: colors.text, fontSize: 15, fontWeight: "800" }, body: { color: colors.muted, fontSize: 11, lineHeight: 17, textAlign: "center", marginTop: 8 }, info: { backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border, borderRadius: 17, padding: 16, marginTop: 18 }, label: { color: colors.muted, fontSize: 10, fontWeight: "800", letterSpacing: 1.2 }, infoTitle: { color: colors.text, fontSize: 16, fontWeight: "800", marginTop: 7 } });
